apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-config
data:
  REDIS_URL: redis://redis-service.default.svc.cluster.local:6379
  KAFKA_URL: kafka.default.svc.cluster.local:9092
  MAIN_TOPIC: persist
  JWT_SECRET: secret
