apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  REDIS_URL: redis://redis-service.default.svc.cluster.local:6379
  JWT_SECRET: secret
  DB_URL: postgresql://postgres:mysecretpassword@db-service.default.svc.cluster.local:5432/chatify